import { defineConfig } from "vitepress";

const base = process.env.BASE_PATH || "/";

export default defineConfig({
  lang: "zh-CN",
  title: "论文精读",
  description: "跨学科论文的中文精读, 数学推导, 证据审计和批判性分析.",
  base,
  cleanUrls: true,
  lastUpdated: true,
  markdown: {
    math: true,
    image: {
      lazyLoading: true,
    },
  },
  head: [
    ["meta", { name: "robots", content: "noindex, nofollow, noarchive" }],
    ["meta", { name: "theme-color", content: "#fbfaf6" }],
    [
      "script",
      {},
      `;(() => {
        const appearanceKey = "vitepress-theme-appearance";
        if (localStorage.getItem(appearanceKey) === null) {
          localStorage.setItem(appearanceKey, "light");
        }
      })()`,
    ],
  ],
  themeConfig: {
    siteTitle: "论文精读",
    outline: {
      level: [2, 3],
      label: "本页目录",
    },
    search: {
      provider: "local",
      options: {
        translations: {
          button: {
            buttonText: "搜索",
            buttonAriaLabel: "搜索文档",
          },
          modal: {
            noResultsText: "没有找到相关内容",
            resetButtonTitle: "清除查询",
            footer: {
              selectText: "选择",
              navigateText: "切换",
              closeText: "关闭",
            },
          },
        },
      },
    },
    nav: [
      { text: "首页", link: "/" },
      { text: "论文库", link: "/papers/" },
      { text: "UMA", link: "/papers/uma/" },
      { text: "阅读说明", link: "/guide/reading-method" },
    ],
    sidebar: [
      {
        text: "开始阅读",
        items: [
          { text: "论文库", link: "/papers/" },
          { text: "如何使用精读站", link: "/guide/reading-method" },
        ],
      },
      {
        text: "MatterGen",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/mattergen/mattergen/" },
          { text: "1. 符号, 晶体表示与扩散基础", link: "/mattergen/mattergen/diffusion-basics" },
          { text: "2. 原子类型扩散与周期坐标起点", link: "/mattergen/mattergen/atom-types" },
          { text: "3. 周期坐标与晶格扩散", link: "/mattergen/mattergen/geometry-diffusion" },
          { text: "4. Score 网络与联合损失", link: "/mattergen/mattergen/network-loss" },
          { text: "5. 属性适配与条件引导", link: "/mattergen/mattergen/guidance" },
          { text: "6. 数据, S.U.N. 与无条件生成", link: "/mattergen/mattergen/evaluation" },
          { text: "7. 条件生成与实验验证", link: "/mattergen/mattergen/conditional-evidence" },
          { text: "8. 局限与后续争议", link: "/mattergen/mattergen/critique" },
          { text: "原文定位索引", link: "/mattergen/mattergen/source-map" },
        ],
      },
      {
        text: "生成模型与锂电材料",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/mattergen/battery-generative/" },
          { text: "1. 发现流程与筛选漏斗", link: "/mattergen/battery-generative/workflow" },
          { text: "2. 化学空间与生成偏差", link: "/mattergen/battery-generative/chemical-space" },
          { text: "3. 全部数学公式", link: "/mattergen/battery-generative/formulas" },
          { text: "4. 十个候选与声子检验", link: "/mattergen/battery-generative/candidates" },
          { text: "5. 补充材料与数据审计", link: "/mattergen/battery-generative/supplementary" },
          { text: "6. 证据边界与总体评价", link: "/mattergen/battery-generative/critique" },
          { text: "原文定位与数据来源", link: "/mattergen/battery-generative/source-map" },
        ],
      },
      {
        text: "MatterSim",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/mattergen/mattersim/" },
          { text: "1. 问题与核心思想", link: "/mattergen/mattersim/problem" },
          { text: "2. 数据与主动学习", link: "/mattergen/mattersim/data" },
          { text: "3. 模型与数学", link: "/mattergen/mattersim/model" },
          { text: "4. 证据与实验", link: "/mattergen/mattersim/evidence" },
          { text: "5. 迁移与定制", link: "/mattergen/mattersim/adaptation" },
          { text: "6. 局限与审读结论", link: "/mattergen/mattersim/critique" },
          { text: "原文定位索引", link: "/mattergen/mattersim/source-map" },
        ],
      },
      {
        text: "MatterSim-MT",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/mattersim-mt/" },
          { text: "1. 从势能面到多任务", link: "/papers/mattersim-mt/problem" },
          { text: "2. 数据, 主动学习与 scaling", link: "/papers/mattersim-mt/data" },
          { text: "3. 模型结构与损失函数", link: "/papers/mattersim-mt/model" },
          { text: "4. 势能面能力与迁移", link: "/papers/mattersim-mt/pes-evidence" },
          { text: "5. 多任务物理案例", link: "/papers/mattersim-mt/multitask" },
          { text: "6. 局限与审读结论", link: "/papers/mattersim-mt/critique" },
          { text: "原文定位索引", link: "/papers/mattersim-mt/source-map" },
        ],
      },
      {
        text: "DPA-2",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/dpa2/" },
          { text: "1. LAM 工作流与问题定义", link: "/papers/dpa2/workflow" },
          { text: "2. 数据集与标签协议", link: "/papers/dpa2/data" },
          { text: "3. PES, 环境矩阵与平滑截断", link: "/papers/dpa2/formulation" },
          { text: "4. Repinit 与对称化", link: "/papers/dpa2/repinit" },
          { text: "5. Repformer 与平滑注意力", link: "/papers/dpa2/repformer" },
          { text: "6. 单任务与多任务损失", link: "/papers/dpa2/training" },
          { text: "7. 零样本与少样本证据", link: "/papers/dpa2/generalization" },
          { text: "8. 蒸馏与物理验证", link: "/papers/dpa2/distillation" },
          { text: "9. 表征, 消融与能量守恒", link: "/papers/dpa2/representation" },
          { text: "10. 局限与审读结论", link: "/papers/dpa2/critique" },
          { text: "原文定位索引", link: "/papers/dpa2/source-map" },
        ],
      },
      {
        text: "eSEN",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/esen/" },
          { text: "1. 从静态误差到物性要求", link: "/papers/esen/problem" },
          { text: "2. 守恒力与能量漂移界", link: "/papers/esen/theory" },
          { text: "3. eSEN 架构与训练策略", link: "/papers/esen/model" },
          { text: "4. 三类平滑性设计与消融", link: "/papers/esen/smoothness" },
          { text: "5. 材料稳定性与热导率", link: "/papers/esen/materials" },
          { text: "6. 声子, 位移与假性改善", link: "/papers/esen/phonons" },
          { text: "7. 分子结果, 效率与审读", link: "/papers/esen/critique" },
          { text: "原文定位索引", link: "/papers/esen/source-map" },
        ],
      },
      {
        text: "原子模拟基础模型",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/fm-atomistic/" },
          { text: "1. Foundation model 资格判据", link: "/papers/fm-atomistic/definition" },
          { text: "2. MLIP 架构谱系与共同骨架", link: "/papers/fm-atomistic/architecture" },
          { text: "3. 物理归纳偏置与 bitter lesson", link: "/papers/fm-atomistic/inductive-bias" },
          { text: "4. 现有 MLIP 的失效模式", link: "/papers/fm-atomistic/failure-modes" },
          { text: "5. 大规模数据版图", link: "/papers/fm-atomistic/datasets" },
          { text: "6. 数据缺口与标签质量", link: "/papers/fm-atomistic/data-quality" },
          { text: "7. Pre-training 与 post-training", link: "/papers/fm-atomistic/training" },
          { text: "8. 如何证明模型 foundational", link: "/papers/fm-atomistic/evaluation" },
          { text: "9. OMol25, UMA 与审读结论", link: "/papers/fm-atomistic/frontier" },
          { text: "原文定位索引", link: "/papers/fm-atomistic/source-map" },
        ],
      },
      {
        text: "PET-MAD",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/pet-mad/" },
          { text: "1. MAD 数据集与一致 DFT", link: "/papers/pet-mad/data" },
          { text: "2. PET 架构, 训练与 LoRA", link: "/papers/pet-mad/model" },
          { text: "3. 跨数据集 benchmark 与速度", link: "/papers/pet-mad/benchmarks" },
          { text: "4. LLPR 不确定性与传播", link: "/papers/pet-mad/uncertainty" },
          { text: "5. 离子输运与 GaAs 熔点", link: "/papers/pet-mad/transport-melting" },
          { text: "6. 合金偏析与液态水", link: "/papers/pet-mad/alloy-water" },
          { text: "7. NMR 晶体学与 BTO", link: "/papers/pet-mad/nmr-bto" },
          { text: "8. Fine-tuning 学习曲线", link: "/papers/pet-mad/finetuning" },
          { text: "9. Direct force 与 MTS", link: "/papers/pet-mad/direct-force" },
          { text: "10. 全部编号公式", link: "/papers/pet-mad/formulas" },
          { text: "11. 局限与审读结论", link: "/papers/pet-mad/critique" },
          { text: "原文定位索引", link: "/papers/pet-mad/source-map" },
        ],
      },
      {
        text: "DPA3",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/dpa3/" },
          { text: "1. LAM 问题与设计目标", link: "/papers/dpa3/problem" },
          { text: "2. Line graph series", link: "/papers/dpa3/ligs" },
          { text: "3. 消息传递与原子能模型", link: "/papers/dpa3/architecture" },
          { text: "4. 守恒性, 对称性与 smoothness", link: "/papers/dpa3/physics" },
          { text: "5. Problem-oriented benchmarks", link: "/papers/dpa3/benchmarks" },
          { text: "6. Scaling law 与架构消融", link: "/papers/dpa3/scaling" },
          { text: "7. DPA-3.1-3M 与 zero-shot", link: "/papers/dpa3/lam" },
          { text: "8. Dataset encoding 与 fine-tuning", link: "/papers/dpa3/multitask" },
          { text: "9. 推理效率与成本", link: "/papers/dpa3/efficiency" },
          { text: "10. 全部编号公式", link: "/papers/dpa3/formulas" },
          { text: "11. 局限与审读结论", link: "/papers/dpa3/critique" },
          { text: "原文定位索引", link: "/papers/dpa3/source-map" },
        ],
      },
      {
        text: "UMA",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/uma/" },
          { text: "1. 训练数据与 DFT tasks", link: "/papers/uma/data" },
          { text: "2. eSEN backbone 与全局条件", link: "/papers/uma/architecture" },
          { text: "3. Mixture of Linear Experts", link: "/papers/uma/mole" },
          { text: "4. 两阶段训练与算力", link: "/papers/uma/training" },
          { text: "5. IsoFLOP scaling laws", link: "/papers/uma/scaling" },
          { text: "6. 推理速度与显存", link: "/papers/uma/inference" },
          { text: "7. 材料与声子证据", link: "/papers/uma/materials" },
          { text: "8. 催化与 AdsorbML", link: "/papers/uma/catalysis" },
          { text: "9. 分子与药物设计", link: "/papers/uma/molecules" },
          { text: "10. 分子晶体与 MOFs", link: "/papers/uma/crystals-mofs" },
          { text: "11. 版本与 diatomic 失效", link: "/papers/uma/versions" },
          { text: "12. 全部编号公式", link: "/papers/uma/formulas" },
          { text: "13. 局限与审读结论", link: "/papers/uma/critique" },
          { text: "原文定位索引", link: "/papers/uma/source-map" },
        ],
      },
      {
        text: "FlashTP",
        collapsed: false,
        items: [
          { text: "总览与阅读路线", link: "/papers/flashtp/" },
          { text: "1. MLIP 的四阶段计算链", link: "/papers/flashtp/pipeline" },
          { text: "2. CG 张量积的数学结构", link: "/papers/flashtp/tensor-product" },
          { text: "3. 3 类性能瓶颈", link: "/papers/flashtp/bottlenecks" },
          { text: "4. 融合, 稀疏与 Path Aggregation", link: "/papers/flashtp/optimizations" },
          { text: "5. 实现与 GPU 映射", link: "/papers/flashtp/implementation" },
          { text: "6. 微基准与端到端证据", link: "/papers/flashtp/evaluation" },
          { text: "7. 局限与审读结论", link: "/papers/flashtp/critique" },
          { text: "原文定位索引", link: "/papers/flashtp/source-map" },
        ],
      },
      {
        text: "专题入口",
        collapsed: true,
        items: [
          { text: "MatterGen", link: "/mattergen/" },
          { text: "MLIP", link: "/mlip/" },
        ],
      },
    ],
    socialLinks: [
      { icon: "github", link: "https://github.com/TomWhite-tgz/essays" },
    ],
    lastUpdated: {
      text: "最后更新",
      formatOptions: {
        dateStyle: "medium",
        timeStyle: "short",
      },
    },
    docFooter: {
      prev: "上一篇",
      next: "下一篇",
    },
    darkModeSwitchLabel: "外观",
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部",
  },
});
